### PR TITLE
Allow uppercase in language specifications

### PR DESCRIPTION
**Pull request by yatil**
When using uppercase in language definitions on the HTML or body element (for example `pt-BR`), AblePlayer compares it with a list of available languages: 

https://github.com/ableplayer/ableplayer/blob/master/scripts/translation.js#L4

As this list is in lowercase, no match is found. 

This Pull Request transforms the readings from the DOM to lowercase before the comparison which should fix the issue.

### CODE REVIEW

**Comment by yatil** [comment]
Reference: https://github.com/w3c/wai-video-standards-and-benefits/pull/61#issuecomment-533420414

**Comment by terrill** [comment]
@yatil sorry it's taken so long to get back to you about this. Can you resubmit this pull request on the develop branch? Thanks!

**Comment by terrill** [comment]
@yatil I want ahead and made this fix in 6673ef01c12560bd04ff4e0e1159c2df17e4e8bb rather than wait since it's only two changed lines of code. I gave you a shout out in the commit message. Thanks!

**Comment by yatil** [comment]
@terrill Perfect, thanks!

**Pull request closed without merging**
