### PR TITLE
Adding Bahasa Indonesia (id) translation

### PR DESCRIPTION
**Pull request by frirasyidi**
Bahasa Indonesia is Indonesian language

### CODE REVIEW

**Comment by terrill** [comment]
Thanks @frirasyidi . Do you mind resubmitting this pull request on the **develop** branch?

**Comment by frirasyidi** [comment]
Sure @terrill , I've moved it to the **develop** branch.

**Comment by terrill** [comment]
Thanks @frirasyidi ! This is very much appreciated!

**Comment by frirasyidi** [comment]
Happy to help!

**Pull request merged**
