### PR TITLE
fix cue-payload-ending 'whitespace line' regex

### LINKED ISSUE #348: WebVTT parser returns error if voice tag is on line by itself
Given these examples: 

**Example 1**
00:11.000 --> 00:13.000
<v Roger Bingham> We are in New York City

**Example 2**
00:11.000 --> 00:13.000
<v Roger Bingham> 
We are in New York City

The first is ok, but the second returns an "Invalid WebVTT file" error via webvtt.js > parseCue(). In the  example, the value of **nextLine** is expected to be a timestamp but it's a string ("We are in New York City"), which triggers the error. 

All of the examples of voice tags in the WebVTT spec have the voice tag followed by text on the same line, and this arrangement makes sense. However, the spec doesn't seem to **require** text on the same line as a voice tag, and the above is valid according to the [Live WebVTT Validator](https://quuz.org/webvtt/). 

Having the voice tag on a line by itself might in fact be common since the [DCMP Captioning Key](http://www.captioningkey.org/speaker_identification.html) calls for speaker identification to be on a line by itself, wrapped in parentheses.  Caption files created in other formats that conform to the Captioning Key recommendations might be converted into WebVTT with a simple search/replace, resulting in a voice tag on a line by itself. 

 I'm not having any luck figuring out where within the parser things are going awry, so if anyone can figure it out, please send a pull request!

### PR DESCRIPTION
**Pull request by conorom**
Fixes #348

### CODE REVIEW

**Comment by terrill** [comment]
@conorom thanks for submitting this PR. However, I'm not seeing an impact on #348.  Example 2 in that issue still causes a WebVTT parse error.

**Comment by xerc** [comment]
`cherry-pick` https://github.com/xerc/ableplayer/commit/c421a38bd56a788f483e36448d591cb23c1f8ed4

**Comment by jeanem** [comment]
@conorom  - thank you for the pull request. It appears your fix was included with the work on another issue - see commit #cad1ef3f8560, but with testing the #348 issue persists. I'll go ahead and close this pull request. I attempted a fix in another function in the file to remove the trailing spaces - see PR #601.

**Comment by xerc** [comment]
check https://github.com/xerc/ableplayer/commit/c421a38bd56a788f483e36448d591cb23c1f8ed4 there is more optim. posbl.

**Pull request closed without merging**
